# in file diagram.json, we can see the (devkit) board type: board-esp32-devkit-c-v4,
# it contains esp32-wroom-32 module, referenced by https://www.espressif.com/en/products/devkits

[wokwi]
version = 1
elf = ".pio/build/esp32/firmware.elf"
firmware = ".pio/build/esp32/firmware.bin"
gdbServerPort=3333